sudo: true

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/composer/cache
    - $TRAVIS_BUILD_DIR/vendor/composer/cache

services:
  - mysql
  
matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
#    - php: 7.3
#      env: WP_VERSION=latest
#    - php: 7.2
#      env: WP_VERSION=latest WP_MULTISITE=1
#    - php: 7.1
#      env: WP_VERSION=latest
#    - php: 7.0
#      env: WP_VERSION=4.9 WP_COVERAGE=coveralls
#    - php: 5.6
#     env: WP_VERSION=latest
    - php: 7.2
      env: WP_TRAVISCI=phpcs

before_install:
  - export PATH="$HOME/bin:$PATH"
 
install:
  # Install an older version of PHPUnit if we're running old versions of WP.
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]] || [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then
      composer require "phpunit/phpunit=5.7.*"
    fi

  # Install our Composer dependencies
  - composer install --prefer-dist --no-interaction

before_script:
  - mkdir -p build/logs
  - chmod +x script/*
  - script/setup

  # disable xdebug if not coverage
  - if [[ $WP_COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] && [[ $WP_COVERAGE == "" ]]; then
      script/cibuild-phpunit
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] && [[ "$WP_COVERAGE" == "coveralls" ]] ; then
      script/cibuild-phpunit-coverage
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      script/cibuild-phpcs
    fi

after_success:
  - |
    if [[ "$WP_COVERAGE" == "coveralls" ]] ; then
      script/coveralls
    fi
